---
- name: Create application folder
  file:
    name: "/opt/status/src"
    state: directory
    owner: "{{ ansible_user }}"
- name: Retrieve application source files
  git:
    clone: yes
    force: yes
    dest: "/tmp/status"
    repo: "http://github.com/jimrigsbee/api.git"
- name: Copy application files
  copy:
    dest: "/opt/status/src/{{ item }}"
    src: "/tmp/status/{{ item }}"
    owner: "{{ ansible_user }}"
    mode: 0644
    remote_src: true
  with_items:
    - requirements.txt
    - server.py
    - wsgi.py
- name: Upgrade pip
  pip:
    name: pip
    state: latest
- name: Install python virtualenv
  pip:
    name: virtualenv
    state: present
    version: 20.0.18
- name: Allow nginx to access non-standard port
  shell: |
    semanage port -a -t http_port_t -p tcp 30904
    semanage port -m -t http_port_t -p tcp 30904
    semanage port -a -t http_port_t -p tcp 8081
    semanage port -m -t http_port_t -p tcp 8081

- name: Install firewalld
  yum:
    name:
      - firewalld
    state: installed

- name: Ensure firewalld is running
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Open Firewall for reporting use
  firewalld:
    port: 30904/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Install python application as a service
  include_role:
    name: Stouts.wsgi
  vars:
    python_enabled: false
    nginx_status: "127.0.0.1:8081"
    wsgi_group: nginx
    wsgi_nginx_servernames: "{{ bastion_dns_name }}"
    wsgi_nginx_port: 30904
    wsgi_applications:
    - name: status
      server: gunicorn
      module: wsgi
      pip_requirements: requirements.txt

- name: Fixups for python virutal env created by Stouts
  shell: |
    source /opt/status/env/bin/activate
    chown -R ec2-user:ec2-user /opt/status/env
    wget https://bootstrap.pypa.io/ez_setup.py -O - | python
  become: no

- name: Remove default nginx config to free port 80
  file:
    name: /etc/nginx/conf.d/default.conf
    state: absent

- name: Create runtime folders
  file:
    name: "{{item}}"
    state: directory
    owner: "{{ansible_user}}"
    group: nginx
  with_items:
    - /opt/status/run
    - /opt/status/log

- name: Fix selinux context for nginx access
  shell: |
    semanage fcontext -a -t httpd_sys_rw_content_t "{{item}}(/.*)?"
    restorecon -R -v "{{item}}"
  with_items:
    - /opt/status/run
    - /opt/status/log

- name: Restart nginx for fixups to take effect
  service:
    name: nginx
    state: restarted

- name: Activate application service
  service:
    name: status-wsgi
    state: restarted
    enabled: yes
