---
- setup:
    gather_subset:
      - network

- name: Setup hostname entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ idm_dns_name }}"
    state: present

- name: Uninstall IdM for idempotency
  shell: |
    curl http://localhost
    if [ $? -eq 0 ]; then
      ipa-server-install -U --uninstall
    fi
  ignore_errors: true

- name: Configure initial IdM setup
  command: >
    ipa-server-install -U
      --hostname="{{ idm_dns_name | default(ansible_fqdn) }}"
      --domain="{{ idm_domain }}"
      --realm="{{ idm_realm | upper }}"
      --ds-password="{{ idm_dm_password }}"
      --admin-password="{{ idm_admin_password }}"
      --no-host-dns
  notify: Ensure IdM is running at boot
